version: "3"
services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - example.env
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - example.env
    volumes:
      - mydatabase:/var/lib/mysql
    command:
      ["--wait-timeout=10000", "--max-allowed-packet=256M"]

  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot
    restart: always
    environment: 
    - CERTBOT_EMAIL=jeanarts92@gmail.com
    ports:
    - 80:80
    - 443:443
    volumes:
    - nginx_secrets:/etc/letsenscrypt
    - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
    - myportfolio

volumes:
  mydatabase:
  nginx_secrets:
